<a href="https://colab.research.google.com/github/finzawork-dev/ML_Algorithms/blob/main/Linear%2BPolynomial_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import scikit as sk
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
pwd  #print working directory

'/content'

In [ ]:
df = pd.read_csv("/content/Advertising (1).csv")

In [ ]:
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [ ]:
#separate label and features
#dropping sales column to get all features together
X = df.drop("sales", axis=1)  #X is by default features  #axis=1 refer to column and axis = 0 refer to rows

In [ ]:
X #only features columns

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [ ]:
y = df["sales"]  #y is the label
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [ ]:
#To train and test now
from sklearn.model_selection import train_test_split

In [ ]:
#Four variables,
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [ ]:
X_train

        TV  radio  newspaper
169  284.3   10.6        6.4
97   184.9   21.0       22.0
31   112.9   17.4       38.6
12    23.8   35.1       65.9
35   290.7    4.1        8.5
..     ...    ...        ...
106   25.0   11.0       29.7
14   204.1   32.9       46.0
92   217.7   33.5       59.0
179  165.6   10.0       17.6
102  280.2   10.1       21.4

[140 rows x 3 columns]

In [ ]:
y_train

169    15.0
97     15.5
31     11.9
12      9.2
35     12.8
       ...
106     7.2
14     19.0
92     19.4
179    12.6
102    14.8
Name: sales, Length: 140, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
my_model=LinearRegression()

In [ ]:
my_model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = my_model.predict(X_test)
y_pred

array([16.5653963 , 21.18822792, 21.55107058, 10.88923816, 22.20231988,
       13.35556872, 21.19692502,  7.35028523, 13.27547079, 15.12449511,
        9.01443026,  6.52542825, 14.30205991,  8.97026042,  9.45679576,
       12.00454351,  8.91549403, 16.15619251, 10.29582883, 18.72473553,
       19.76821818, 13.77469028, 12.49638908, 21.53501762,  7.60860741,
        5.6119801 , 20.91759483, 11.80627665,  9.08076637,  8.51412012,
       12.17604891,  9.9691939 , 21.73008956, 12.77770578, 18.1011362 ,
       20.07590796, 14.26202556, 20.93826535, 10.83938827,  4.38190607,
        9.51332406, 12.40486324, 10.17045434,  8.09081363, 13.16388427,
        5.2243552 ,  9.28893833, 14.09330719,  8.69024497, 11.66119763,
       15.71848432, 11.63156862, 13.35360735, 11.1531472 ,  6.33636845,
        9.76157954,  9.4195714 , 24.25516546,  7.69519137, 12.15317572])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
MAE = mean_absolute_error(y_test, y_pred)
MAE

1.5116692224549086

In [ ]:
sales_mean = df["sales"].mean()
sales_mean

np.float64(14.0225)

In [ ]:
MAE*100/sales_mean
#10 perecnt error rate

np.float64(10.780311802138767)

In [ ]:
#RMSE
np.sqrt(mean_squared_error(y_test, y_pred))

np.float64(1.9485372043446387)

Polynomial Regression

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error

In [ ]:
df = pd.read_csv("/content/Advertising (1).csv")
X = df.drop("sales", axis = 1)
X

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [ ]:
y = df["sales"]
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
#model is instance of polynomial regression degree 2(quadratic) model that is waiting for data to be trained on
model = PolynomialFeatures(degree = 2 )
#fit_tranform generate new polynomial from inputdata by raising feature to higher form
Extended_X = model.fit_transform(X)
Extended_X

array([[1.00000e+00, 2.30100e+02, 3.78000e+01, ..., 1.42884e+03,
        2.61576e+03, 4.78864e+03],
       [1.00000e+00, 4.45000e+01, 3.93000e+01, ..., 1.54449e+03,
        1.77243e+03, 2.03401e+03],
       [1.00000e+00, 1.72000e+01, 4.59000e+01, ..., 2.10681e+03,
        3.18087e+03, 4.80249e+03],
       ...,
       [1.00000e+00, 1.77000e+02, 9.30000e+00, ..., 8.64900e+01,
        5.95200e+01, 4.09600e+01],
       [1.00000e+00, 2.83600e+02, 4.20000e+01, ..., 1.76400e+03,
        2.78040e+03, 4.38244e+03],
       [1.00000e+00, 2.32100e+02, 8.60000e+00, ..., 7.39600e+01,
        7.48200e+01, 7.56900e+01]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(Extended_X, y, test_size=0.3, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)
MAE = mean_absolute_error(y_test, y_pred)
MAE

0.5905974833808363

In [ ]:
MSE = mean_squared_error(y_test, y_pred)
MSE

0.5231944949055658

In [ ]:
np.sqrt(MSE) #this is RMSE(Root mean square errro)

np.float64(0.7233218473857719)

In [ ]:
RMSE =np.sqrt(mean_squared_error(y_test, y_pred))
RMSE

np.float64(0.7233218473857719)

In [ ]:
train_rmse=[]
test_rmse=[]

for d in range(1,15):

    pol = PolynomialFeatures(degree =d)
    new_pol = pol.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(new_pol, y, test_size=0.3, random_state=42)
    my_model = LinearRegression()
    my_model.fit(X_train, y_train)

    train_pred = my_model.predict(X_train)
    test_pred = my_model.predict(X_test)

    train_rmse.append(np.sqrt(mean_squared_error(y_train, train_pred)))
    test_rmse.append(np.sqrt(mean_squared_error(y_test, test_pred)))

In [ ]:
train_rmse

[np.float64(1.574596830590544),
 np.float64(0.5950712355838923),
 np.float64(0.46887581118220883),
 np.float64(0.36946897017715163),
 np.float64(0.2438220680819992),
 np.float64(0.22508524406437544),
 np.float64(0.2312763165057317),
 np.float64(0.27901936364853647),
 np.float64(0.593367857152165),
 np.float64(0.7107668868287145),
 np.float64(0.7821472673920429),
 np.float64(0.9890141448014518),
 np.float64(1.1049746519377543),
 np.float64(1.2311741413549504)]

In [ ]:
test_rmse

[np.float64(1.9485372043446376),
 np.float64(0.7233218473857719),
 np.float64(0.5392350985714038),
 np.float64(1.303226581940553),
 np.float64(5.946737865824301),
 np.float64(22.043720896372964),
 np.float64(235.5810626653298),
 np.float64(5089.001681968113),
 np.float64(10191.096966780844),
 np.float64(16052.177820664147),
 np.float64(57774.178344702064),
 np.float64(19897.150749470744),
 np.float64(8059.954553846263),
 np.float64(39264.52849705011)]